# In The Name Of God
# ========================================
# [] File Name : Makefile
#
# [] Created By : Parham Alvani (parham.alvani@gmail.com)
# =======================================

CFLAGS=-Wall -O0 -g -std=gnu11

.PHONY: all
all: 2Darray sortfork

2Darray: 2Darray.o
sortfork: sortfork.o

.PHONY: clean
clean:
	rm -f *.o 2Darray sortfork
